### ISSUE TITLE
Any chance of FreeBSD support?

### ISSUE THREAD

**Issue by lrosenman** [mattn/go-ieproxy#15]
I was trying to build thanos (https://github.com/thanos-io/thanos) and ran into a compile issue (https://github.com/thanos-io/thanos/issues/1461)

I can provide access to a FreeBSD box.

**Comment by FUSAKLA** [comment]
Hi @lrosenman , is this still an issue? The one related issue got solved eventually.

**Comment by mattn** [comment]
As far as I can see, thanos already fix the issue. Right?

https://github.com/thanos-io/thanos/pull/1476

**Comment by FUSAKLA** [comment]
Yes, on the Thanos side it is fixed, sorry I just didn't notice what repo the issue is in after following link
