### ISSUE TITLE
Support proxy.pac

### ISSUE THREAD

**Issue by oliverpool** [mattn/go-ieproxy#2]
Hi,

I would also like this library to support `proxy.pac` files (at least for windows).

To do this, I thought of using the [`WinHttpGetProxyForUrl` function](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384097(v=vs.85).aspx) of the `Winhttp.dll` library.

However I don't have any experience with dll calling and I can't get it to work...
Do you have any idea?

```go
func main() {
	var winHttp = syscall.NewLazyDLL("Winhttp.dll")
	var open = winHttp.NewProc("WinHttpOpen")
	var close = winHttp.NewProc("WinHttpCloseHandle")
	var getProxyForUrl = winHttp.NewProc("WinHttpGetProxyForUrl")

	handle, _, err := open.Call(0, 0, 0, 0, 0)
	defer close.Call(handle)

	fmt.Println(err)

	ret, _, err := getProxyForUrl.Call(
		handle,
		uintptr(unsafe.Pointer(syscall.StringToUTF16Ptr("https://www.google.com"))),
		0,
		0,
	)

	fmt.Println(ret) // prints 0
	fmt.Println(err) // prints The parameter is incorrect.

}
```

**Comment by mattn** [comment]
Sounds good to me. But I don't have environment to use proxy.pac.:-(

**Comment by oliverpool** [comment]
The `getProxyForUrl.Call`  (WinHttpGetProxyForUrl function) requires pointers to some structure:
- [`WINHTTP_AUTOPROXY_OPTIONS`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384123(v=vs.85).aspx) as input
- [`WINHTTP_PROXY_INFO`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383912(v=vs.85).aspx) as output

How can I create them in go and pass them to the syscall? (to set the arguments and retrieve the proxy infos)
