### ISSUE TITLE
reloadConf undefined

### ISSUE THREAD

**Issue by eatonphil** [mattn/go-ieproxy#26]
Hey my builds just started failing because `reloadConf undefined` on macos, possibly because of the new release from an hour ago.

```
# github.com/mattn/go-ieproxy
../../../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.2/ieproxy.go:41:9: undefined: reloadConf
```

Maybe you can see it here: https://github.com/multiprocessio/dsq/runs/4771009598?check_suite_focus=true.

Is this a real issue?

**Comment by eatonphil** [comment]
I was able to resolve this in my project by pinning back to 0.0.1. I'm ok with it now. Feel free to keep this open if it's a real bug for 0.0.2 or feel free to close it.

Thanks!

**Comment by sethvargo** [comment]
Yea, there's no build for darwin (Mac), so `reloadConf()` is undefined on OS X.

**Comment by mattn** [comment]
Sorry, I don't have OSX. Anyone can implement this?

**Comment by drakkan** [comment]
I think it could also be useful to automatically run test cases at least on the most common OS, see #28

**Comment by andrei-dascalu** [comment]
wondering if this will be released?
