### ISSUE TITLE
go.mod: upgrade dependency golang.org/x/crypto to latest version to avoid vulnerability

### ISSUE THREAD

**Issue by mswathi-tw** [mattn/go-ieproxy#41]
We are using the latest version (github.com/mattn/go-ieproxy@v0.0.7 ) which internally uses the following library

github.com/mattn/go-ieproxy@v0.0.7 › golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2

This has introduced certain snyk vulnerability **NULL Pointer Dereference** and in order to solve this issue following library version has to be upgraded to golang.org/x/crypto@0.0.0-20201216223049-8b5274cf687f or more.

Can you please upgrade it.

**Comment by mattn** [comment]
Thank you
