### ISSUE TITLE
findProxyForURL with cgo on windows

### ISSUE THREAD

**Issue by chrislusf** [mattn/go-ieproxy#45]
Found a similar problem as https://github.com/mattn/go-ieproxy/pull/43 on windows

```
GOOS=windows go build
# github.com/mattn/go-ieproxy
../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_windows.go:22:6: getConf redeclared in this block
	../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_unix.go:6:6: other declaration of getConf
../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_windows.go:28:6: reloadConf redeclared in this block
	../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_unix.go:10:6: other declaration of reloadConf
../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_windows.go:133:6: overrideEnvWithStaticProxy redeclared in this block
	../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_unix.go:14:6: other declaration of overrideEnvWithStaticProxy
../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/pac_windows.go:9:29: ProxyScriptConf.findProxyForURL redeclared in this block
	../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/pac_unix.go:6:29: other declaration of findProxyForURL
```

**Comment by mattn** [comment]
What is your `go env` ?

**Comment by chrislusf** [comment]
```
> go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/chrislu/Library/Caches/go-build"
GOENV="/Users/chrislu/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/chrislu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/chrislu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/chrislu/go/src/github.com/seaweedfs/seaweedfs/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jv/0rlhdck17jzgt7b3hcnq63mc0000gp/T/go-build247650256=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by chrislusf** [comment]
btw: the build error is here: https://github.com/seaweedfs/seaweedfs/actions/runs/3262244509/jobs/5359129932

**Comment by mattn** [comment]
```
CC="clang"
CXX="clang++"
```
You are using host C compiler. It MUST be cross C compiler for Windows.

**Comment by chrislusf** [comment]
Correct. Need to build for windows with github actions.

**Comment by leeweisberger** [comment]
This is also breaking our release train for windows with github actions

**Comment by muhyuddin** [comment]
> Found a similar problem as #43 on windows
> 
> ```
> GOOS=windows go build
> # github.com/mattn/go-ieproxy
> ../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_windows.go:22:6: getConf redeclared in this block
> 	../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_unix.go:6:6: other declaration of getConf
> ../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_windows.go:28:6: reloadConf redeclared in this block
> 	../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_unix.go:10:6: other declaration of reloadConf
> ../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_windows.go:133:6: overrideEnvWithStaticProxy redeclared in this block
> 	../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/ieproxy_unix.go:14:6: other declaration of overrideEnvWithStaticProxy
> ../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/pac_windows.go:9:29: ProxyScriptConf.findProxyForURL redeclared in this block
> 	../../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.9/pac_unix.go:6:29: other declaration of findProxyForURL
> ```

Any solution? 

Facing the same issue on Linux, compiling for Windows, CGO is enabled.

**Comment by abemedia** [comment]
Had the same issue building on Windows with CGO. 
Reverting to `v0.0.7` fixed the issue so just add the following to your `go.mod` as a temporary workaround:
```
replace github.com/mattn/go-ieproxy => github.com/mattn/go-ieproxy v0.0.7
```
Weirdly this only seemed to affect 386 arch (using `CC=i686-w64-mingw32-gcc` and `CXX=i686-w64-mingw32-g++`). 
Might wanna add a test for that in GitHub actions...
