### ISSUE TITLE
Windows Automatic Pac Lookup fails on Windows 7 due to invalid flags

### ISSUE THREAD

**Issue by lanoxx** [mattn/go-ieproxy#6]
In pac_windows.go:70  we find the following line:

    dwFlags:                fWINHTTP_AUTOPROXY_CONFIG_URL + fWINHTTP_AUTOPROXY_NO_CACHE_CLIENT + fWINHTTP_AUTOPROXY_NO_CACHE_SVC,

The following two flags are causing windows to return a ERROR_INVALID_PARAMETER when I execute the proxy lookup:

 * `fWINHTTP_AUTOPROXY_NO_CACHE_CLIENT`
 * `fWINHTTP_AUTOPROXY_NO_CACHE_SVC`

Removing these flags allows me to resolve the proxy successfully. I am running this on Windows 7.

**Comment by mattn** [comment]
Ah, could you please try with modifing `+` to `|`  ?

**Comment by mattn** [comment]
@oliverpool could you please handle this issue?

**Comment by oliverpool** [comment]
`+` and `|` should give the same result (since the bits are disjoint).

Maybe we could simply remove those flags (I can't remember any reason to bypass the cache...)

**Comment by mattn** [comment]
which one, could you please send me PR ? I don't have environment for proxy using pac.

**Comment by lanoxx** [comment]
Hi,
in pac_windows.go:70 the are currently three flags set, remove the last two:

 * `fWINHTTP_AUTOPROXY_CONFIG_URL` (keep this one)
 * `fWINHTTP_AUTOPROXY_NO_CACHE_CLIENT` (drop this one)
 * `fWINHTTP_AUTOPROXY_NO_CACHE_SVC` (drop this one)

That is how I got it working on my computer yesterday.

**Comment by oliverpool** [comment]
@lanoxx #7 has just been merged into master, could you update and tell us if it fixed your issue?

thanks!

**Comment by lanoxx** [comment]
I updated to my go.mod file and go.sum files to the latest version and it still works. Cudos for the fast fix.
